name: flexurio_erp_core
version: 0.0.1
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"
description: A new Flutter package project.
dependencies:
  animated_check: ^1.0.2
  animated_cross: ^1.0.0
  clipboard: ^0.1.3
  connectivity_plus: ^6.0.5
  currency_text_input_formatter: ^2.1.10
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.5
  easy_localization: ^3.0.7
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.5
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.7.0
  form_field_validator: ^1.1.0
  gap: ^3.0.1
  glass: ^1.0.2+1
  go_router: ^14.3.0
  google_fonts: ^4.0.4
  hive: ^2.2.3
  hydrated_bloc: ^10.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  just_audio: ^0.9.37
  just_audio_windows: ^0.2.1
  lottie: ^3.3.1
  month_picker_dialog: ^4.0.1
  package_info_plus: ^8.0.0
  page_transition: ^2.0.9
  pattern_formatter:
    git:
      url: https://github.com/augustineonu/flutter_pattern_formatter.git
      ref: e310fc81043468b9b2b063bac6122f7dde51b03f
  pdf: ^3.8.4
  pinput: ^2.2.31
  printing: ^5.10.4
  screen_identifier: ^0.0.2
  side_panel: ^0.0.1
  syncfusion_flutter_charts: ^28.1.33
  syncfusion_flutter_datepicker: ^28.1.33
  syncfusion_flutter_xlsio: ^28.1.33
  timeline_tile: ^2.0.0
  visibility_detector: ^0.4.0+2
dev_dependencies:
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  pubspec_dependency_sorter: ^1.0.5
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
  assets:
    - asset/html/
    - asset/svg/
    - asset/svg/extension/
    - asset/gif/
    - asset/sound/
    - asset/image/
    - asset/image/icon/
    - asset/translation/
