name: flx_core_flutter
description: A Flutter package that enables no-code app development with built-in support for JSON parsing, API integrations, and dynamic content rendering.
homepage: https://github.com/flexurio/flx_core_flutter
repository: https://github.com/flexurio/flx_core_flutter
issue_tracker: https://github.com/flexurio/flx_core_flutter/issues

version: 1.0.0-dev.6
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  path_provider: ^2.0.9
  clipboard: ^0.1.3
  connectivity_plus: ^6.0.5
  currency_text_input_formatter: ^2.1.10
  dio: ^5.8.0+1
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.5
  easy_localization: ^3.0.7
  file_picker: ^9.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.5
  toastification: ^3.0.2
  font_awesome_flutter: ^10.7.0
  form_field_validator: ^1.1.0
  gap: ^3.0.1
  glass: ^1.0.2+1
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hydrated_bloc: ^10.0.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.20.2
  just_audio: ^0.9.37
  just_audio_windows: ^0.2.1
  lottie: ^3.3.0
  month_picker_dialog: ^4.0.1
  package_info_plus: ^8.0.0
  page_transition: ^2.0.9
  pattern_formatter: ^4.0.0
  pdf: ^3.8.4
  pinput: ^2.2.31
  printing: ^5.10.4
  screen_identifier: ^0.0.2
  side_panel: ^0.0.1
  syncfusion_flutter_charts: ^28.1.33
  syncfusion_flutter_datepicker: ^28.1.33
  syncfusion_flutter_xlsio: ^28.1.33
  timeline_tile: ^2.0.0
  visibility_detector: ^0.4.0+2
  excel: ^4.0.6
  download: ^1.0.1
dependency_overrides:
  intl: ^0.20.2
dev_dependencies:
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  pubspec_dependency_sorter: ^1.0.5
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
  assets:
    - asset/html/
    - asset/svg/
    - asset/svg/extension/
    - asset/gif/
    - asset/sound/
    - asset/image/
    - asset/image/icon/
    - asset/translation/
