import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

enum DataAction {
  recordAttendance('record_attendance', Icons.check, Colors.green),
  submit('submit', Icons.check, Colors.lightBlue),
  markAsLeader('mark_as_leader', Icons.more_vert, Colors.green),
  remove('remove', Icons.cancel, Colors.green),
  resign('mark_as_resign', Icons.check, Colors.green),
  addToCard('add_to_card', Icons.check, Colors.green),
  activate('activate', Icons.bolt, Colors.orange),
  activatePhaseOut('activate_phase_out', Icons.bolt, Colors.orange),
  add('add', Icons.add, Colors.green),
  applyFilter('apply_filter', Icons.cancel, Colors.orange),
  approve('approve', Icons.check, Colors.green),
  approval('approval', Icons.check, Colors.green),
  approveManager('approve_manager', Icons.check, Colors.green),
  approveCs('approve_cs', Icons.done_all, Colors.green),
  approveFinance('approve_finance', Icons.check, Colors.green),
  approveAccounting('approve_accounting', Icons.check, Colors.green),
  cancel('cancel', Icons.cancel, Colors.grey),
  cancelConfirm('cancel_confirm', Icons.cancel, Colors.grey),
  close('close', Icons.done_all, Colors.green),
  closePO('close_po', Icons.done_all, Colors.green),
  comment('comment', Icons.comment_outlined, Colors.blueGrey),
  confirm('confirm', Icons.check, Colors.green),
  retry('Retry', Icons.refresh, Colors.green),
  confirmFinance('confirm_finance', Icons.done_all, Colors.green),
  accountingConfirm('accounting_confirm', Icons.check, Colors.green),
  accountingReject('accounting_reject', Icons.keyboard_return, Colors.red),
  confirmMarketing('confirm_marketing', Icons.check, Colors.green),
  undoConfirmPPIC('undo_confirm_ppic', Icons.restart_alt, Colors.purple),
  confirmPpic('confirm_ppic', Icons.done_all, Colors.green),
  undoConfirm('undo_confirm', Icons.check, Colors.green),
  undoConfirmAccounting('undo_confirm_accounting', Icons.check, Colors.green),
  create('create', Icons.add, Colors.green),
  placeOrder('place_order', Icons.add, Colors.green),
  createForMaterial('create_for_material', Icons.add, Colors.green),
  createForProduct('create_for_product', Icons.add, Colors.green),
  createSales('create_sales', Icons.add, Colors.green),
  createPayment('create_payment', Icons.add, Colors.green),
  check('check', Icons.analytics_outlined, Colors.blue),
  checkQc('check_qc', Icons.check, Colors.green),
  createSalesOrder('Create SO', Icons.add, Colors.green),
  createActual('create_actual', Icons.add, Colors.green),
  createAdditional('create_additional', Icons.add, Colors.green),
  createMR('create_mr', Icons.add, Colors.green),
  editAdditional('edit_additional', Icons.edit, Colors.orange),
  editHalalCertificate('edit_halal_certificate', Icons.edit, Colors.green),
  none('', Icons.edit, Colors.transparent),
  deactivate('deactivate', Icons.cancel, Colors.red),
  deactivatePhaseOut('Deactivate Phase Out', Icons.add, Colors.green),
  delivery('Delivery', Icons.archive, Colors.green),
  deliveryActual('Delivery Actual', Icons.local_shipping, Colors.green),
  delete('delete', Icons.delete_outline_rounded, Colors.red),
  refresh('refresh', Icons.refresh, Colors.green),
  release('release', Icons.arrow_outward, Colors.green),
  realization('Realization', Icons.switch_access_shortcut_add, Colors.green),
  reject('reject', Icons.keyboard_return, Colors.red),
  rejectManager('Reject Manager', Icons.keyboard_return, Colors.red),
  rejectCs('Reject CS', Icons.keyboard_return, Colors.red),
  rejectAccounting('Reject Manager', Icons.keyboard_return, Colors.red),
  rejectFinance('Reject Finance', Icons.keyboard_return, Colors.red),
  rejectProcurement('Reject Procurement', Icons.keyboard_return, Colors.red),
  next('next', Icons.abc, Colors.orange),
  back('back', Icons.abc, Colors.orange),
  viewDetail('view_detail', Icons.list, Colors.blue),
  convert('Convert', Icons.autorenew_rounded, Colors.blue),
  edit('edit', Icons.edit_outlined, Colors.orange),
  leadTime('lead_time', Icons.pending_actions, Colors.blue),
  update('Update', Icons.edit_outlined, Colors.orange),
  updateDate('Update', Icons.calendar_month, Colors.orange),
  updateActualStart('Update Actual Start', Icons.calendar_month, Colors.green),
  updateActualEnd('Update Actual End', Icons.calendar_month, Colors.orange),
  exportExcelProductPrice(
    'Export Excel Product Price',
    FontAwesomeIcons.fileArrowDown,
    Colors.orange,
  ),
  exportExcel('export_excel', FontAwesomeIcons.fileExcel, Colors.indigo),
  export('Export', FontAwesomeIcons.fileDownload, Colors.orange),
  exportPdf('export_pdf', FontAwesomeIcons.filePdf, Colors.indigo),
  exportJobsheet('export_jobsheet', FontAwesomeIcons.filePdf, Colors.redAccent),
  exportBatch('export_batch', FontAwesomeIcons.filePdf, Colors.redAccent),
  print('print', FontAwesomeIcons.filePdf, Colors.redAccent),
  exportDocument('Export Document', FontAwesomeIcons.filePdf, Colors.redAccent),
  insertPrice('Insert Price', Icons.monetization_on_outlined, Colors.green),
  exportDeliveryOrder(
    'Export Delivery Order',
    FontAwesomeIcons.car,
    Colors.green,
  ),
  finish('finish', Icons.cancel, Colors.grey),
  login('login', Icons.cancel, Colors.orange),
  logout('logout', Icons.cancel, Colors.orange),
  open('open', Icons.replay_outlined, Colors.orange),
  printPDF('print_pdf', Icons.print, Colors.orange),
  printInvoice('Print Invoice', Icons.print, Colors.orange),
  printDeliveryOrder('print_delivery_order', Icons.print, Colors.orange),
  upload('upload', Icons.upload_rounded, Colors.orange),
  validate('validate', Icons.check, Colors.green),
  verify('verify', Icons.cancel, Colors.orange),
  view('view', Icons.remove_red_eye, Colors.blue),
  viewImage('view_image', Icons.remove_red_eye, Colors.blue),
  viewCalendar('View', Icons.calendar_month, Colors.blue),
  viewGroup('View Group', FontAwesomeIcons.layerGroup, Colors.blue),
  hide('hide', Icons.restart_alt, Colors.purple),
  rework('Rework', Icons.restart_alt, Colors.purple),
  reprocess('Reprocess', Icons.cloud_sync_outlined, Colors.grey),
  active('Active', Icons.check, Colors.grey),
  archive('Archive', Icons.archive, Colors.grey),
  notActive('Not active', Icons.cancel, Colors.red),
  moving('Moving', Icons.moving_outlined, Colors.orange),
  search('search', Icons.search, Colors.blue),
  undoConfirmMarketing(
    'Undo Confirm Marketing',
    Icons.restart_alt,
    Colors.purple,
  ),
  cancelRework(
    'Cancel Rework',
    Icons.cancel_schedule_send_outlined,
    Colors.red,
  ),

  showApproveVendorList(
    'Show Approve Supplier List',
    Icons.assignment_turned_in,
    Colors.blue,
  ),
  showPermission(
    'Show Permission',
    Icons.app_registration,
    Colors.blue,
  ),
  showWorkHour('Show Work Hour', FontAwesomeIcons.clock, Colors.blue),
  showEmployee('Show Employee', Icons.group_outlined, Colors.blue),
  showPrice('Show Price', Icons.point_of_sale, Colors.green),
  showDiscount('Show Discount', Icons.percent, Colors.green),
  showFormulation('Show Formulation', FontAwesomeIcons.tablets, Colors.blue),
  showSchedule('Show Schedule', FontAwesomeIcons.calendarDay, Colors.blue);

  const DataAction(this._title, this.icon, this.color);
  final String _title;
  final IconData icon;
  final Color color;

  String get title => _title.tr();
  String get id => _title;

  bool get isEdit => this == DataAction.edit;
  bool get isCreate => this == DataAction.create;
}
